site_name: Документация MkDocs
site_description: Тестовая публикация документации (статический сайт) с помощью MkDocs и GitHub Pages (+Swagger UI).

theme: material

plugins:
  - macros

nav:
  - Главная: index.md
  - Для пользователей:
    - Быстрый старт: quickstart.md
  - Для разработчиков:
    - Справочник API: swagger.html
    - Примеры использования API: examples.md
  - О проекте: about.md
